# Generated by Django 3.2 on 2024-01-31 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pong_game', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
