version: '3.8'

services:
  db:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  nginx:
    build:
      context: nginx
    restart: always
    ports:
     - "1300:1300"
    depends_on:
     - db
    volumes:
     - ./nginx/modsecurity.conf:/etc/nginx/modsecurity.conf
     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
     - ./nginx/startup.sh:/startup.sh
    command: /bin/bash /startup.sh
  web:
    build:
      context: backend
      dockerfile: Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - VAULT_ADDR=http://0.0.0.0:8200
      - VAULT_TOKEN=root
    depends_on:
      - db
      - vault

  vault:
    image: hashicorp/vault:latest
    container_name: vault
    ports:
      - "8200:8200"
    environment:
    # Development mode - runs in-memory storage backend and
    #                    won't persist data across container restarts
      - VAULT_DEV_ROOT_TOKEN_ID=root

volumes:
  postgres-data:
