version: '3.8'

services:
  web:
    container_name: web
    networks:
      - ft_trans
    build:
      context: backend
      dockerfile: Dockerfile
    # command: daphne -u /usr/src/daphne_sock/daphne.sock -p 8000 -b 0.0.0.0 django_project.asgi:application
    command: sh -c "for i in $(seq 1 7); do echo 'Waiting for all containers to be done...'; sleep 1; done; python3 manage.py runserver 0.0.0.0:8000"
    # command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
      - daphne-sock:/usr/src/daphne_sock
      # - static_volume:/code/mystaticfiles
      - vault_data_web:/run/secrets:ro
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - vault

  db:
    container_name: postgres
    networks:
      - ft_trans
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

  nginx:
    container_name: nginx
    networks:
      - ft_trans
    build:
      context: nginx
    restart: always
    ports:
     - "8433:433"
    depends_on:
     - db
    volumes:
     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
     - ./nginx/modsecurity.conf:/etc/nginx/modsec/modsecurity.conf
     - ./nginx/startup.sh:/startup.sh
     - ./nginx/main.conf:/etc/nginx/modsec/main.conf
     - daphne-sock:/usr/src/daphne_sock
    #  - static_volume:/code/mystaticfiles:ro
    command: /bin/bash /startup.sh

  vault:
    container_name: vault
    user: '0:0'
    networks:
      - ft_trans
    build:
      context: vault
    ports:
      - "8200:8200"
    env_file:
      - .env
    volumes:
      - vault_data_web:/vault/data/skey
      - vault_data:/vault/data
    depends_on:
      - db
    cap_add:
      - IPC_LOCK
    command: /bin/sh /start_up.sh

volumes:
  vault_data_web:
  postgres-data:
  daphne-sock:
  static_volume:
  vault_data:

networks:
  ft_trans:
    driver: bridge
