version: '3.8'

services:
  web:
    container_name: web
    networks:
      - ft_trans
    build:
      context: backend
      dockerfile: Dockerfile
    command: sh ./start_up.sh
    volumes:
      - ./backend:/code
      - daphne-sock:/usr/src/daphne_sock
      - static_volume:/code/mystaticfiles
      - media_volume:/code/media
      - vault_data_web:/run/secrets:ro
    depends_on:
      vault:
        condition: service_healthy

  db:
    container_name: postgres
    networks:
      - ft_trans
    image: postgres
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    container_name: nginx
    networks:
      - ft_trans
    build:
      context: nginx
    restart: always
    ports:
     - "8433:433"
    depends_on:
      vault:
        condition: service_healthy
    volumes:
     - daphne-sock:/usr/src/daphne_sock
     - static_volume:/code/mystaticfiles:ro
     - media_volume:/code/media
    command: /bin/bash /startup.sh

  vault:
    container_name: vault
    user: '0:0'
    networks:
      - ft_trans
    build:
      context: vault
    env_file:
      - .env
    volumes:
      - vault_data_web:/vault/data/skey
      - vault_data:/vault/data
    depends_on:
      db:
        condition: service_healthy
    cap_add:
      - IPC_LOCK
    command: /bin/sh /start_up.sh
    healthcheck:
      test: ["CMD", "vault", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  media_volume:
  vault_data_web:
  postgres-data:
  daphne-sock:
  static_volume:
  vault_data:

networks:
  ft_trans:
    driver: bridge
