version: '3.8'

services:
  web:
    container_name: web
    build:
      context: backend
      dockerfile: Dockerfile
    # command: daphne -u /usr/src/daphne_sock/daphne.sock -p 8000 -b 0.0.0.0 django_project.asgi:application
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - daphne-sock:/usr/src/daphne_sock
      - static_volume:/code/mystaticfiles
      - vault_data:/run/secrets/keys:ro
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - vault

  db:
    container_name: postgres
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"

  nginx:
    container_name: nginx
    build:
      context: nginx
    restart: always
    ports:
     - "8433:8433"
    depends_on:
     - db
    volumes:
     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
     - ./nginx/modsecurity.conf:/etc/nginx/modsec/modsecurity.conf
     - ./nginx/startup.sh:/startup.sh
     - ./nginx/main.conf:/etc/nginx/modsec/main.conf
     - daphne-sock:/usr/src/daphne_sock
     - static_volume:/code/mystaticfiles:ro
    command: /bin/bash /startup.sh

  vault:
    container_name: vault
    build:
      context: vault
    ports:
      - "8200:8200"
    env_file:
      - .env
    volumes:
      - vault_data:/keys
    cap_add:
      - IPC_LOCK
    command: /bin/sh /start_up.sh

volumes:
  postgres-data:
  daphne-sock:
  static_volume:
  vault_data:
