version: '3.8'

services:
  db:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  nginx:
    image: nginx:latest
    restart: always
    ports:
     - "8443:8443"
    depends_on:
     - web
    volumes:
     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
     - ./nginx/startup.sh:/startup.sh
    command: /bin/bash /startup.sh

  web:
    build:
      context: backend
      dockerfile: Dockerfile
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=root
      - ENCRYPTION_KEY_NAME=key_token
    depends_on:
      - db
      - vault

  vault:
<<<<<<< HEAD
    image: hashicorp/vault:latest
=======
    image: hashicorp/vault
>>>>>>> game_websockets
    ports:
      - "8200:8200"
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=root
<<<<<<< HEAD
=======
  
>>>>>>> game_websockets

volumes:
  postgres-data:
