# Generated by Django 3.2.24 on 2024-02-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20240220_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='nickName',
            field=models.CharField(default=models.CharField(default='', max_length=255, unique=True), max_length=255),
        ),
    ]
