# Generated by Django 3.2.24 on 2024-03-13 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_matchhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='nickName',
            new_name='nickname',
        ),
    ]
