# Generated by Django 3.2.24 on 2024-03-13 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_matchhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='nickName',
            field=models.CharField(default=models.CharField(default='', max_length=10, unique=True), max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
    ]
