# Generated by Django 3.2.24 on 2024-03-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20240312_1542'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='alias',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nickName',
            field=models.CharField(default=models.CharField(default='', max_length=255, unique=True), max_length=255),
        ),
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
