# Generated by Django 3.2.24 on 2024-03-13 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_userprofile_nickname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='nickname',
            new_name='alias',
        ),
    ]
