# Generated by Django 3.2.24 on 2024-03-15 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20240314_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='games_won',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='alias',
            field=models.CharField(default='', max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default='', max_length=12, unique=True),
        ),
    ]
