# Generated by Django 3.2 on 2024-02-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pong_game', '0002_delete_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField()),
                ('game_type', models.CharField(choices=[('CL', 'Classic'), ('EX', 'EXTRA')], default='CL', max_length=2)),
            ],
        ),
    ]
