# Generated by Django 3.2.24 on 2024-03-01 13:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pong_game', '0003_gameinstance'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('player_one', models.CharField(default='player_one', max_length=255)),
                ('player_two', models.CharField(default='player_two', max_length=255)),
                ('player_one_score', models.IntegerField(default=0)),
                ('player_two_score', models.IntegerField(default=0)),
                ('winner', models.CharField(default='winner', max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='GameInstance',
        ),
    ]
