# Generated by Django 3.2.24 on 2024-03-06 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pong_game', '0004_auto_20240301_0906'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MatchHistory',
        ),
    ]
